version: "3.7"

services:
  server:
    container_name: dct-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /dct-backend/
    working_dir: /dct-backend/
    command: ./command.sh
